spring.application.name=smart-travel-disruption-platform

# Conexiune PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/travel_disruption
spring.datasource.username=travel_user
spring.datasource.password=travel_pass
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Flyway
spring.flyway.enabled=true